In [10]:
#import libraries
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [63]:
#load the dataset
df=pd.read_csv('/content/BankNote_Authentication.csv')

In [64]:
df.head()

   variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [65]:
df.shape

(1372, 5)

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   variance  1372 non-null   float64
 1   skewness  1372 non-null   float64
 2   curtosis  1372 non-null   float64
 3   entropy   1372 non-null   float64
 4   class     1372 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 53.7 KB

In [67]:
df.describe()

          variance     skewness     curtosis      entropy        class
count  1372.000000  1372.000000  1372.000000  1372.000000  1372.000000
mean      0.433735     1.922353     1.397627    -1.191657     0.444606
std       2.842763     5.869047     4.310030     2.101013     0.497103
min      -7.042100   -13.773100    -5.286100    -8.548200     0.000000
25%      -1.773000    -1.708200    -1.574975    -2.413450     0.000000
50%       0.496180     2.319650     0.616630    -0.586650     0.000000
75%       2.821475     6.814625     3.179250     0.394810     1.000000
max       6.824800    12.951600    17.927400     2.449500     1.000000

In [68]:
#print numerical and categorical variables
# Numerical variables
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

print("Numerical Variables:")
print(list(numerical_cols))

Numerical Variables:
['variance', 'skewness', 'curtosis', 'entropy', 'class']

In [69]:
# Categorical variables
categorical_cols = df.select_dtypes(include=['object', 'category']).columns
print("\nCategorical Variables:")
print(list(categorical_cols))

Categorical Variables:
[]

In [70]:
#identify duplicate rows
print("no of duplicate rows:",df.duplicated().sum())

no of duplicate rows: 24

In [71]:
#remove duplicates
df.drop_duplicates(inplace=True)
df.shape

(1348, 5)

In [72]:
#identify null values
df.isnull().sum()

variance    0
skewness    0
curtosis    0
entropy     0
class       0
dtype: int64

In [73]:
#seperate features and target
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [74]:
#covert target variable fertilizers_status
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [75]:
#Testing and training
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [76]:
# Identify categorical columns in X
categorical_cols_X = X.select_dtypes(include=['object', 'category']).columns

In [77]:
# Apply one-hot encoding to categorical columns in X_train and X_test
X_train = pd.get_dummies(X_train, columns=categorical_cols_X, drop_first=True)
X_test = pd.get_dummies(X_test, columns=categorical_cols_X, drop_first=True)

In [78]:
# Ensure that X_train and X_test have the same columns after one-hot encoding
X_train, X_test = X_train.align(X_test, join='outer', axis=1, fill_value=0)

In [79]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [80]:
from sklearn.svm import LinearSVC
#model buiding
model=LinearSVC(random_state=42)
model.fit(X_train,y_train)

LinearSVC(random_state=42)

In [81]:
#Predictions on test data
y_pred=model.predict(X_test)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

Accuracy: 0.9925925925925926

In [82]:
#confusion matrix
confusion_mat=confusion_matrix(y_test,y_pred)
print("Confusion Matrix:")
print(confusion_mat)

Confusion Matrix:
[[145   2]
 [  0 123]]

In [83]:
#CLASSIFICATION REPORT
classification_rep=classification_report(y_test,y_pred)
print("Classification Report:")
print(classification_rep)

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       147
           1       0.98      1.00      0.99       123

    accuracy                           0.99       270
   macro avg       0.99      0.99      0.99       270
weighted avg       0.99      0.99      0.99       270